# 예외2 - 예외 던지기
## 예외의 강제
API를 사용할 때 설계자 의도에 따라 예외를 반드시 처리해야 하는 경우가 있다.
```java
import java.io.*;
public class CheckedExceptionDemo {
    public static void main(String[] args) {
        BufferedReader bReader = new BufferedReader(new FileReader("out.txt"));
        String input = bReader.readLine();
        System.out.println(input); 
    }
}
```
현재로선 어려운 코드니 이해는 차처하자. 그냥 `out.txt` 파일을 읽어서 화면에 출력하는 내용이다. 
이 코드를 실행시키려면 `out.txt`파일을 프로젝트의 루트 디렉토리에 위치시켜야 한다. 
이클립스 기반으로 아래<br><br>
![2066](https://user-images.githubusercontent.com/96712990/161682066-2334c847-893c-4198-9458-92f072382b81.png)<br><br>
이 위치에 파일이 존재해야 한다.<br>
맨 위 코드를 컴파일하면 에러가 발생하면서<br>
```
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
    Unhandled exception type FileNotFoundException
    Unhandled exception type IOException
 
    at org.opentutorials.javatutorials.exception.CheckedExceptionDemo.main(CheckedExceptionDemo.java:5)
```
<br>
컴파일이 되지 않는다. 차례로 살펴보자.
```
Unhandled exception type FileNotFoundException
```
이것은 아래 로직에 대한 예외처리가 필요하다는 뜻이다. 
```java
new FileReader("out.txt")
```
`FileReader`라는 클래스를 API문서에서 찾아보자. 
`FileReader`의 생성자를 문서에서 찾아보면<br><br>
![2067](https://user-images.githubusercontent.com/96712990/161684493-d52b426c-c302-4b83-a3e0-444e3b64d17e.png)
<br><br>
같은 부분이 있다.<br>
Throws는 굳이 번역하자면 던진다는 뜻이다. 내용인 즉 `FileReader`의 인자 `fileName`의 값에 해당하는 파일이 
디렉토리이거나 어떤 이유로 사용할 수 없다면 `FileNotFoundException` 에러를 발생시킨다는 의미이다. 
<br><br>
`FileReader`의 생성자가 동작할 때 파일을 열 수 없는 경우, 생성자 `FileReader`에서는 이 문제를 처리할 수 없다. 
따라서 이에 대한 처리를 생성자의 사용자에게 위임해야 하며, 이 행위를 '던진다(throw)'고 하는 것이다. 
그렇기 때문에 API 사용자는 예외처리를 반드시 해야 FileReader 클래스를 사용할 수 있다.<br>
+ `BufferedReader` 클래스의 `readLine` 메소드는 `IOException` 에러를 발생시킬 수 있기 때문에 이것도 고려해 수정한다.
```java
import java.io.*;
public class CheckedExceptionDemo {
    public static void main(String[] args) {
        try { // 예외처리 추가
            BufferedReader bReader = new BufferedReader(new FileReader("out.txt"));
        } catch (FileNotFoundException e) {
            e.printStackTrace(); 
        }
           try{
            String input = bReader.readLine();
        } catch (IOException e){ //IOexception 예외처리
            e.printStackTrace();
        }  
        String input = bReader.readLine();
        System.out.println(input); 
    }
}
```
맙소사, 그래도 에러가 발생한다. 다시 살펴보자. 변수 bReader를 보면, 이 변수는 첫 번째 try의 중괄호 안에서 선언되고 있다. 
이 변수는 두 번째 try 중괄호에서 다시 사용되는데, 
서로 다른 중괄호이기 때문에 11행에서 bReader를 쓰려면 코드를 수정해야 한다.
```java
import java.io.*;
public class CheckedExceptionDemo {
    public static void main(String[] args) {
        BufferedReader bReader = null; // 수정
        String input = null; //수정. 중괄호 밖에서 선언.
        try {
            bReader = new BufferedReader(new FileReader("out.txt"));
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        try{
            input = bReader.readLine();
        } catch (IOException e){
            e.printStackTrace();
        }       
        System.out.println(input); 
    }
}
```
## throw 와 throws
이제 본격적으로 throws를 배워보자. throw는 예외처리를 다음 사용자에게 넘기는 것이다. 그럼 다음 사용자가 누굴까? 코드로 알아보자.<br>


